// <auto-generated />
namespace YouConf.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddConferenceDataToStoreInDatabaseInsteadOfTableStorage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConferenceDataToStoreInDatabaseInsteadOfTableStorage));
        
        string IMigrationMetadata.Id
        {
            get { return "201305190458405_AddConferenceDataToStoreInDatabaseInsteadOfTableStorage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
